exp_name: revalidate cuda transform
split_ratio:
- 0.9
- 0.08
- 0.02
batch_size: 96
epoch: 4
lr: 0.0009
fused_optimizer: none
num_workers: 7
persistent_workers: true
pin_memory: true
non_blocking: true
cudnn_benchmark: false
cuda_transform: true
cuda_if: true
channels_last: true
antialias: false
test_enable: false
use_profiler: false
