output_dir: results/manual_test
data:
  test_dir: images/test_sf/unknown
  class_map: map.json
  batch_size: 128
  split_ratio: [1]
  split_index: 0
model:
  checkpoint: maptest.pth
runtime:
  cuda_dataset: true
  autocast: true
image_size: [224, 224]
normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
output:
  csv: results.csv
