exp_name: batch size 128 to 96
split_ratio:
- 0.9
- 0.08
- 0.02
batch_size: 96
epoch: 4
lr: 0.0009
num_workers: 7
persistent_workers: true
pin_memory: true
non_blocking: true
cuda_if: true
test_enable: false
use_profiler: true
